In [1]:
# numpy生成各类随机数记录
# 以下内容复现与记录于 https://blog.csdn.net/xtingjie/article/details/71068032
import numpy as np

1. rand函数,产生(0,1)之间的随机数，形状为shape;
2. randn函数,产生标准正态分布，均值为0， 方差为1， 参数也是shape;
3. randint函数，产生指定范围的随机数，前两个参数表示范围，最后一个参数是size=(shape)

In [2]:
np.random.rand(3,4)

array([[0.19483362, 0.91670156, 0.4399618 , 0.94921376],
       [0.38746957, 0.11800901, 0.53948757, 0.9657558 ],
       [0.35052798, 0.49652603, 0.70189962, 0.09240917]])

In [4]:
np.random.randn(3,4)

array([[-1.76236155, -1.21069216, -0.18050335,  0.41750398],
       [-0.02556024,  1.00287226,  1.55230305, -0.24289601],
       [-0.39850797,  1.96651807,  0.34362083,  0.54968736]])

In [5]:
np.random.randint(2,5,(3,4))

array([[4, 2, 3, 2],
       [4, 3, 4, 2],
       [2, 2, 3, 2]])

1. uniform产生特定上下界的随机数    numpy.random.uniform(low=0.0, high=1.0, size=None)
2. normal产生满足高斯分布的随机数   numpy.random.normal(loc=mean, scale=standard_deviation, size=None)
3. poisson产生满足泊松分布的随机数   numpy.random.poisson(lam=1.0, size=None)

In [6]:
np.random.uniform(low=1.0, high=2.0, size=(3,4))

array([[1.03047611, 1.10710598, 1.00668615, 1.80903454],
       [1.81071181, 1.53326624, 1.06284027, 1.06866312],
       [1.27354217, 1.01129166, 1.26985659, 1.41643385]])

In [7]:
np.random.normal(loc=2, scale=3, size=(3,4))

array([[ 0.25761882,  1.66297642,  6.90398747,  3.9584744 ],
       [-0.61252431,  3.11737043,  7.1029655 ,  5.68738939],
       [-0.19456782,  9.27584867,  3.49723265,  0.51259952]])

In [8]:
np.random.poisson(lam=1.0, size=(3,4))

array([[4, 0, 0, 1],
       [0, 2, 0, 1],
       [1, 1, 0, 1]])