In [13]:
import torch

In [14]:
token_ids = torch.LongTensor([1,2,3,4,0,0,0])

In [15]:
length = 4
max_len = 7

In [16]:
inverse_idx = [i for i in range(length-1, -1, -1)]
inverse_idx = inverse_idx + list(range(length, max_len, 1))
inverse_idx = torch.LongTensor(inverse_idx)
inverse_idx

tensor([3, 2, 1, 0, 4, 5, 6])

In [17]:
inverse_tokenids = token_ids.index_select(0, inverse_idx)
inverse_tokenids

tensor([4, 3, 2, 1, 0, 0, 0])

In [18]:
# 获取embedding后实际内容的逆向部分

In [19]:
batch, max_len, dim = 3, 7, 2
lengths = [4,5,6]
token_emb = torch.randint(1, 6, (3,7, 2))
token_emb

tensor([[[5, 3],
         [3, 1],
         [3, 3],
         [5, 1],
         [3, 5],
         [2, 3],
         [3, 2]],

        [[4, 2],
         [1, 1],
         [3, 3],
         [2, 3],
         [2, 4],
         [4, 5],
         [2, 5]],

        [[4, 3],
         [1, 3],
         [5, 4],
         [1, 1],
         [5, 3],
         [3, 3],
         [2, 2]]])

In [24]:
idx = [[j for j in range(lengths[i]-1, -1, -1)] + list(range(lengths[i], max_len, 1)) for i in range(batch)]
idx

[[3, 2, 1, 0, 4, 5, 6], [4, 3, 2, 1, 0, 5, 6], [5, 4, 3, 2, 1, 0, 6]]

In [26]:
inverse_idx = torch.LongTensor(idx)
inverse_idx

tensor([[3, 2, 1, 0, 4, 5, 6],
        [4, 3, 2, 1, 0, 5, 6],
        [5, 4, 3, 2, 1, 0, 6]])

In [35]:
inverse_token_emb = [token_emb[i].index_select(0, inverse_idx[i]) for i in range(batch)]
inverse_token_emb

[tensor([[5, 1],
         [3, 3],
         [3, 1],
         [5, 3],
         [3, 5],
         [2, 3],
         [3, 2]]), tensor([[2, 4],
         [2, 3],
         [3, 3],
         [1, 1],
         [4, 2],
         [4, 5],
         [2, 5]]), tensor([[3, 3],
         [5, 3],
         [1, 1],
         [5, 4],
         [1, 3],
         [4, 3],
         [2, 2]])]

In [39]:
torch.stack(inverse_token_emb, dim=0)

tensor([[[5, 1],
         [3, 3],
         [3, 1],
         [5, 3],
         [3, 5],
         [2, 3],
         [3, 2]],

        [[2, 4],
         [2, 3],
         [3, 3],
         [1, 1],
         [4, 2],
         [4, 5],
         [2, 5]],

        [[3, 3],
         [5, 3],
         [1, 1],
         [5, 4],
         [1, 3],
         [4, 3],
         [2, 2]]])