In [5]:
# 稀疏矩阵 scipy.sparse.csr_matrix解释
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([[0,1,0,2,0],[1,1,0,2,0],[2,0,5,0,0]])
arr

array([[0, 1, 0, 2, 0],
       [1, 1, 0, 2, 0],
       [2, 0, 5, 0, 0]])

In [11]:
b = csr_matrix(arr)



In [10]:
# 非零元素个数
b.nnz

7

In [7]:
# 稀疏矩阵中元素
b.data

array([1, 2, 1, 1, 2, 2, 5], dtype=int32)

In [12]:
# 每行非零元素对应的列索引值组成的数组
b.indices

array([1, 3, 0, 1, 3, 0, 2], dtype=int32)

In [9]:
# 第一个元素为0；之后每个元素表示稀疏矩阵中每行元素(非零元素)个数累计结果
b.indptr

array([0, 2, 5, 7], dtype=int32)