In [21]:
"""
1. 注意slaler.fit和transform的数据都需要经过reshape(-1,1)的变换
"""
from sklearn.preprocessing import StandardScaler
import numpy as np

data_1 = [1,2,3,4,5]
data_1 = np.array(data).reshape(-1,1)
data_2 = [6,9,12,15,18]
data_2 = np.array(data).reshape(-1,1)
scaler = StandardScaler()


In [35]:
scaler_1 = scaler.fit(data_1)
res = scaler_1.transform(data_1)
print (res)
print (type(res))

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
<class 'numpy.ndarray'>


In [31]:
scaler_2 = scaler.fit(data_2)
print ("scaler_1:")
scaler_1.transform(data_2)


scaler_1:


array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [32]:
print ("scaler_2:")
scaler_2.transform(data_1)

scaler_2:


array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])