In [7]:
import torch
import torch.nn as nn
torch.manual_seed(224)

# 如果tensor1和tensor2都是一维，则进行点乘操作

In [6]:
a = torch.randint(1,5,(5,))
b = torch.randint(1,5,(5,))
c = torch.matmul(a,b)
print (a)
print (b)
print (c)

tensor([3, 2, 1, 2, 4])
tensor([4, 2, 4, 1, 3])
tensor(34)


# 如果tensor1和tensor2都是二维，则进行矩阵乘法操作，类似torch.mm

In [9]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(3,4))
print (a)
print (b)

tensor([[1, 2, 4],
        [2, 3, 3]])
tensor([[2, 1, 2, 4],
        [4, 2, 4, 1],
        [3, 3, 1, 1]])


In [10]:
c = torch.matmul(a,b)
c

tensor([[22, 17, 14, 10],
        [25, 17, 19, 14]])

In [11]:
d = torch.mm(a,b)
d

tensor([[22, 17, 14, 10],
        [25, 17, 19, 14]])

In [16]:
a = torch.randint(1,5,(3,4))
b = torch.randint(1,5,(4,)) # b和a中的每一维依次做点乘
print (a)
print (b)
c = torch.matmul(a,b)
print (c)
print (c.shape)

tensor([[2, 4, 3, 4],
        [2, 3, 1, 4],
        [2, 1, 1, 4]])
tensor([3, 1, 4, 2])
tensor([30, 21, 19])
torch.Size([3])


# batch matrix的乘法，类似于torch.bmm

In [20]:
a = torch.randint(1,5,(2,2,3))
b = torch.randint(1,5,(2,3,4)) # b和a中的每一维依次做点乘
print (a)
print (b)
c = torch.matmul(a,b)
print (c)
print (c.shape)

tensor([[[3, 4, 4],
         [2, 4, 4]],

        [[2, 1, 1],
         [3, 3, 2]]])
tensor([[[2, 2, 2, 2],
         [3, 1, 2, 4],
         [3, 1, 4, 3]],

        [[3, 3, 2, 1],
         [3, 3, 3, 3],
         [4, 4, 4, 4]]])
tensor([[[30, 14, 30, 34],
         [28, 12, 28, 32]],

        [[13, 13, 11,  9],
         [26, 26, 23, 20]]])
torch.Size([2, 2, 4])


In [21]:
torch.bmm(a,b)

tensor([[[30, 14, 30, 34],
         [28, 12, 28, 32]],

        [[13, 13, 11,  9],
         [26, 26, 23, 20]]])

# [batch,s,m,n] * [batch,s,n,k]的矩阵乘法

In [5]:
import torch
a = torch.randint(1,5,(2, 3, 4, 2))
b = torch.randint(1,5,(2, 3, 2, 4))
c = torch.matmul(a,b)

In [6]:
c.shape

torch.Size([2, 3, 4, 4])