In [19]:
# torch embedding加载词向量与训练词向量
import torch.nn as nn
import numpy as np

"""
    加载词向量    https://lyb3b.github.io/2017/12/12/pytorch%E5%8A%A0%E8%BD%BD%E5%B7%B2%E8%AE%AD%E7%BB%83%E5%A5%BD%E7%9A%84word-embedding/ 
"""
embedding = nn.Embedding(10, 3)
embedding.weight

Parameter containing:
tensor([[ 0.0868, -0.7985,  0.4803],
        [-2.3194,  0.2405, -0.5583],
        [-0.3008, -1.0022,  0.0396],
        [ 1.7283,  2.3268,  1.2617],
        [-1.4875, -0.0531,  0.8992],
        [ 0.0131,  0.9614, -0.5288],
        [ 0.6142, -0.4470, -0.3539],
        [-1.0055,  2.6115,  0.9762],
        [-1.4793, -0.7439, -0.0839],
        [ 0.1275,  0.4703,  0.4038]], requires_grad=True)

In [20]:
pre_word_embeds = np.random.rand(10, 3)
pre_word_embeds

array([[0.49044602, 0.56424827, 0.03615954],
       [0.37477997, 0.10547466, 0.75048304],
       [0.81672492, 0.53194183, 0.90856952],
       [0.60222615, 0.18638102, 0.92762805],
       [0.13413598, 0.63928688, 0.28781084],
       [0.44410181, 0.79891153, 0.60051962],
       [0.50259244, 0.42316361, 0.5855377 ],
       [0.52200995, 0.26287504, 0.96355167],
       [0.3351849 , 0.14383304, 0.41424016],
       [0.54760257, 0.12300922, 0.82974449]])

In [21]:
embedding.weight = nn.Parameter(torch.FloatTensor(pre_word_embeds))
embedding.weight

Parameter containing:
tensor([[0.4904, 0.5642, 0.0362],
        [0.3748, 0.1055, 0.7505],
        [0.8167, 0.5319, 0.9086],
        [0.6022, 0.1864, 0.9276],
        [0.1341, 0.6393, 0.2878],
        [0.4441, 0.7989, 0.6005],
        [0.5026, 0.4232, 0.5855],
        [0.5220, 0.2629, 0.9636],
        [0.3352, 0.1438, 0.4142],
        [0.5476, 0.1230, 0.8297]], requires_grad=True)

以上是通过nn.Embedding()加载已训练好向量的方法；根据[文档](https://pytorch.org/docs/stable/nn.html)， nn.Embedding()是A simple lookup table that stores embeddings of a **fixed dictionary** and size., 因此无法对此进行训练，如果要训练，则应该使用ebm = nn.Embedding.from_pretrained(init_weight, freeze=False)，这样可以对emb.weight进行训练。

训练后，可通过model.state_dict()['embed.weight']获取参数。