In [4]:
# torch.view与torch.reshape区别  https://blog.csdn.net/u010665216/article/details/78569370 (然而没懂)
import torch
a = torch.randn(2,3)
a

tensor([[-0.1100, -0.7695,  1.5661],
        [ 0.7538,  0.8951,  1.2276]])

In [5]:
a.reshape(1,-1)

tensor([[-0.1100, -0.7695,  1.5661,  0.7538,  0.8951,  1.2276]])

In [6]:
a

tensor([[-0.1100, -0.7695,  1.5661],
        [ 0.7538,  0.8951,  1.2276]])

In [7]:
a.view(1,-1)

tensor([[-0.1100, -0.7695,  1.5661,  0.7538,  0.8951,  1.2276]])

In [8]:
a

tensor([[-0.1100, -0.7695,  1.5661],
        [ 0.7538,  0.8951,  1.2276]])